# Generated by Django 5.0.1 on 2024-02-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
